# Generated by Django 3.2.5 on 2021-10-22 14:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(help_text='Field ini tidak boleh dikosongkan.', max_length=50)),
                ('perkenalan_singkat', models.CharField(help_text='Field ini tidak boleh dikosongkan.', max_length=150)),
                ('gambar_profil', models.ImageField(blank=True, help_text='Field ini boleh dikosongkan.', null=True, upload_to='profiles/')),
                ('biograpi', models.TextField(blank=True, help_text='Field ini boleh dikosongkan.', null=True)),
                ('dibuat', models.DateTimeField(auto_now_add=True)),
                ('diupdate', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_skill', models.CharField(blank=True, help_text='Field ini boleh dikosongkan.', max_length=50, null=True)),
                ('dibuat', models.DateTimeField(auto_now_add=True)),
                ('diupdate', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(blank=True, help_text='Field ini boleh dikosongkan.', null=True, on_delete=django.db.models.deletion.CASCADE, to='profiles.profile')),
            ],
        ),
    ]
