# Generated by Django 3.2.5 on 2021-10-22 14:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='user',
            field=models.OneToOneField(blank=True, help_text='Field ini boleh dikosongkan.', null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='profile',
            name='gambar_profil',
            field=models.ImageField(blank=True, default='profiles/user-default.png', help_text='Field ini boleh dikosongkan.', null=True, upload_to='profiles/'),
        ),
    ]
